# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_make_raw_data_vector_for_probabilities <- function(gp, B_bit_prob = 16L, i_snp_1_based = 1L) {
    .Call('_rrbgen_rcpp_make_raw_data_vector_for_probabilities', PACKAGE = 'rrbgen', gp, B_bit_prob, i_snp_1_based)
}

#' @export
rcpp_place_gp_t_into_output <- function(gp_t, to_out, i_sample, nSNPs, B_bit_prob = 16L) {
    invisible(.Call('_rrbgen_rcpp_place_gp_t_into_output', PACKAGE = 'rrbgen', gp_t, to_out, i_sample, nSNPs, B_bit_prob))
}

#' @export
rcpp_convert_raw_probabilities_to_double_probabilities <- function(data_raw_for_probs, N, B_bit_prob, is_missing) {
    .Call('_rrbgen_rcpp_convert_raw_probabilities_to_double_probabilities', PACKAGE = 'rrbgen', data_raw_for_probs, N, B_bit_prob, is_missing)
}

#' @export
rcpp_build_giant_output_vector <- function(per_var_L_vid, per_var_L_gdb, Layout, CompressedSNPBlocks, binary_vid_list, binary_gpd_list, per_var_C_raw, per_var_D_raw) {
    .Call('_rrbgen_rcpp_build_giant_output_vector', PACKAGE = 'rrbgen', per_var_L_vid, per_var_L_gdb, Layout, CompressedSNPBlocks, binary_vid_list, binary_gpd_list, per_var_C_raw, per_var_D_raw)
}

