# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_return_same_int <- function(hello) {
    .Call('_rrbgen_rcpp_return_same_int', PACKAGE = 'rrbgen', hello)
}

#' @export
rcpp_make_raw_data_vector_for_probabilities <- function(gp_sub, B_bit_prob = 16L) {
    .Call('_rrbgen_rcpp_make_raw_data_vector_for_probabilities', PACKAGE = 'rrbgen', gp_sub, B_bit_prob)
}

#' @export
rcpp_place_gp_t_into_output <- function(gp_t, to_out, i_sample, nSNPs, B_bit_prob = 16L) {
    invisible(.Call('_rrbgen_rcpp_place_gp_t_into_output', PACKAGE = 'rrbgen', gp_t, to_out, i_sample, nSNPs, B_bit_prob))
}

#' @export
rcpp_convert_raw_probabilities_to_double_probabilities <- function(data_raw_for_probs, N, B_bit_prob, is_missing) {
    .Call('_rrbgen_rcpp_convert_raw_probabilities_to_double_probabilities', PACKAGE = 'rrbgen', data_raw_for_probs, N, B_bit_prob, is_missing)
}

